apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-uat
  labels:
    app: hello-uat
spec:
  selector:
    matchLabels:
      app: hello-uat
  template:
    metadata:
      labels:
        app: hello-uat
        tier: hello-uat
    spec:
      containers:
      - name: hello
        image: afroz2022/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: hello
---
apiVersion: v1
kind: Service
metadata:
  name: hello-uat
  labels:
    app: hello-uat
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: hello
    tier: hello
  type: LoadBalancer
